const timeZones = [
  {
    countryCode: "AF",
    countryName: "Afghanistan",
    timeZone: "Asia/Kabul",
    gmtOffset: "UTC +04:30",
    selected: "",
  },
  {
    countryCode: "AL",
    countryName: "Albania",
    timeZone: "Europe/Tirane",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "DZ",
    countryName: "Algeria",
    timeZone: "Africa/Algiers",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "AS",
    countryName: "American Samoa",
    timeZone: "Pacific/Pago_Pago",
    gmtOffset: "UTC -11:00",
    selected: "",
  },
  {
    countryCode: "AD",
    countryName: "Andorra",
    timeZone: "Europe/Andorra",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "AO",
    countryName: "Angola",
    timeZone: "Africa/Luanda",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "AI",
    countryName: "Anguilla",
    timeZone: "America/Anguilla",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/Casey",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/Davis",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/DumontDUrville",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/Mawson",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/McMurdo",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/Palmer",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/Rothera",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/Syowa",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/Troll",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    timeZone: "Antarctica/Vostok",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "AG",
    countryName: "Antigua and Barbuda",
    timeZone: "America/Antigua",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/Buenos_Aires",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/Catamarca",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/Cordoba",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/Jujuy",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/La_Rioja",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/Mendoza",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/Rio_Gallegos",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/Salta",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/San_Juan",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/San_Luis",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/Tucuman",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    timeZone: "America/Argentina/Ushuaia",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "AM",
    countryName: "Armenia",
    timeZone: "Asia/Yerevan",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "AW",
    countryName: "Aruba",
    timeZone: "America/Aruba",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Antarctica/Macquarie",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Adelaide",
    gmtOffset: "UTC +09:30",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Brisbane",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Broken_Hill",
    gmtOffset: "UTC +09:30",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Darwin",
    gmtOffset: "UTC +09:30",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Eucla",
    gmtOffset: "UTC +08:45",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Hobart",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Lindeman",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Lord_Howe",
    gmtOffset: "UTC +10:30",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Melbourne",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Perth",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    timeZone: "Australia/Sydney",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "AT",
    countryName: "Austria",
    timeZone: "Europe/Vienna",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "AZ",
    countryName: "Azerbaijan",
    timeZone: "Asia/Baku",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "BS",
    countryName: "Bahamas",
    timeZone: "America/Nassau",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "BH",
    countryName: "Bahrain",
    timeZone: "Asia/Bahrain",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "BD",
    countryName: "Bangladesh",
    timeZone: "Asia/Dhaka",
    gmtOffset: "UTC +06:00",
    selected: "",
  },
  {
    countryCode: "BB",
    countryName: "Barbados",
    timeZone: "America/Barbados",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "BY",
    countryName: "Belarus",
    timeZone: "Europe/Minsk",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "BE",
    countryName: "Belgium",
    timeZone: "Europe/Brussels",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "BZ",
    countryName: "Belize",
    timeZone: "America/Belize",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "BJ",
    countryName: "Benin",
    timeZone: "Africa/Porto-Novo",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "BM",
    countryName: "Bermuda",
    timeZone: "Atlantic/Bermuda",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "BT",
    countryName: "Bhutan",
    timeZone: "Asia/Thimphu",
    gmtOffset: "UTC +06:00",
    selected: "",
  },
  {
    countryCode: "BO",
    countryName: "Bolivia, Plurinational State of",
    timeZone: "America/La_Paz",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "BQ",
    countryName: "Bonaire, Sint Eustatius and Saba",
    timeZone: "America/Kralendijk",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "BA",
    countryName: "Bosnia and Herzegovina",
    timeZone: "Europe/Sarajevo",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "BW",
    countryName: "Botswana",
    timeZone: "Africa/Gaborone",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Araguaina",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Bahia",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Belem",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Boa_Vista",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Campo_Grande",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Cuiaba",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Eirunepe",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Fortaleza",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Maceio",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Manaus",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Noronha",
    gmtOffset: "UTC -02:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Porto_Velho",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Recife",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Rio_Branco",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Santarem",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    timeZone: "America/Sao_Paulo",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "IO",
    countryName: "British Indian Ocean Territory",
    timeZone: "Indian/Chagos",
    gmtOffset: "UTC +06:00",
    selected: "",
  },
  {
    countryCode: "BN",
    countryName: "Brunei Darussalam",
    timeZone: "Asia/Brunei",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "BG",
    countryName: "Bulgaria",
    timeZone: "Europe/Sofia",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "BF",
    countryName: "Burkina Faso",
    timeZone: "Africa/Ouagadougou",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "BI",
    countryName: "Burundi",
    timeZone: "Africa/Bujumbura",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "KH",
    countryName: "Cambodia",
    timeZone: "Asia/Phnom_Penh",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "CM",
    countryName: "Cameroon",
    timeZone: "Africa/Douala",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Atikokan",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Blanc-Sablon",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Cambridge_Bay",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Creston",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Dawson",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Dawson_Creek",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Edmonton",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Fort_Nelson",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Glace_Bay",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Goose_Bay",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Halifax",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Inuvik",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Iqaluit",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Moncton",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Rankin_Inlet",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Regina",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Resolute",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/St_Johns",
    gmtOffset: "UTC -02:30",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Swift_Current",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Toronto",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Vancouver",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Whitehorse",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    timeZone: "America/Winnipeg",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "CV",
    countryName: "Cape Verde",
    timeZone: "Atlantic/Cape_Verde",
    gmtOffset: "UTC -01:00",
    selected: "",
  },
  {
    countryCode: "KY",
    countryName: "Cayman Islands",
    timeZone: "America/Cayman",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "CF",
    countryName: "Central African Republic",
    timeZone: "Africa/Bangui",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "TD",
    countryName: "Chad",
    timeZone: "Africa/Ndjamena",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "CL",
    countryName: "Chile",
    timeZone: "America/Punta_Arenas",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "CL",
    countryName: "Chile",
    timeZone: "America/Santiago",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "CL",
    countryName: "Chile",
    timeZone: "Pacific/Easter",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "CN",
    countryName: "China",
    timeZone: "Asia/Shanghai",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "CN",
    countryName: "China",
    timeZone: "Asia/Urumqi",
    gmtOffset: "UTC +06:00",
    selected: "",
  },
  {
    countryCode: "CX",
    countryName: "Christmas Island",
    timeZone: "Indian/Christmas",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "CC",
    countryName: "Cocos (Keeling) Islands",
    timeZone: "Indian/Cocos",
    gmtOffset: "UTC +06:30",
    selected: "",
  },
  {
    countryCode: "CO",
    countryName: "Colombia",
    timeZone: "America/Bogota",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "KM",
    countryName: "Comoros",
    timeZone: "Indian/Comoro",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "CG",
    countryName: "Congo",
    timeZone: "Africa/Brazzaville",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "CD",
    countryName: "Congo, the Democratic Republic of the",
    timeZone: "Africa/Kinshasa",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "CD",
    countryName: "Congo, the Democratic Republic of the",
    timeZone: "Africa/Lubumbashi",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "CK",
    countryName: "Cook Islands",
    timeZone: "Pacific/Rarotonga",
    gmtOffset: "UTC -10:00",
    selected: "",
  },
  {
    countryCode: "CR",
    countryName: "Costa Rica",
    timeZone: "America/Costa_Rica",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "HR",
    countryName: "Croatia",
    timeZone: "Europe/Zagreb",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "CU",
    countryName: "Cuba",
    timeZone: "America/Havana",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "CW",
    countryName: "Curaçao",
    timeZone: "America/Curacao",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "CY",
    countryName: "Cyprus",
    timeZone: "Asia/Famagusta",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "CY",
    countryName: "Cyprus",
    timeZone: "Asia/Nicosia",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "CZ",
    countryName: "Czech Republic",
    timeZone: "Europe/Prague",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "CI",
    countryName: "Côte d'Ivoire",
    timeZone: "Africa/Abidjan",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "DK",
    countryName: "Denmark",
    timeZone: "Europe/Copenhagen",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "DJ",
    countryName: "Djibouti",
    timeZone: "Africa/Djibouti",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "DM",
    countryName: "Dominica",
    timeZone: "America/Dominica",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "DO",
    countryName: "Dominican Republic",
    timeZone: "America/Santo_Domingo",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "EC",
    countryName: "Ecuador",
    timeZone: "America/Guayaquil",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "EC",
    countryName: "Ecuador",
    timeZone: "Pacific/Galapagos",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "EG",
    countryName: "Egypt",
    timeZone: "Africa/Cairo",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "SV",
    countryName: "El Salvador",
    timeZone: "America/El_Salvador",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "GQ",
    countryName: "Equatorial Guinea",
    timeZone: "Africa/Malabo",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "ER",
    countryName: "Eritrea",
    timeZone: "Africa/Asmara",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "EE",
    countryName: "Estonia",
    timeZone: "Europe/Tallinn",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "ET",
    countryName: "Ethiopia",
    timeZone: "Africa/Addis_Ababa",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "FK",
    countryName: "Falkland Islands (Malvinas)",
    timeZone: "Atlantic/Stanley",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "FO",
    countryName: "Faroe Islands",
    timeZone: "Atlantic/Faroe",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "FJ",
    countryName: "Fiji",
    timeZone: "Pacific/Fiji",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "FI",
    countryName: "Finland",
    timeZone: "Europe/Helsinki",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "FR",
    countryName: "France",
    timeZone: "Europe/Paris",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "GF",
    countryName: "French Guiana",
    timeZone: "America/Cayenne",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "PF",
    countryName: "French Polynesia",
    timeZone: "Pacific/Gambier",
    gmtOffset: "UTC -09:00",
    selected: "",
  },
  {
    countryCode: "PF",
    countryName: "French Polynesia",
    timeZone: "Pacific/Marquesas",
    gmtOffset: "UTC -09:30",
    selected: "",
  },
  {
    countryCode: "PF",
    countryName: "French Polynesia",
    timeZone: "Pacific/Tahiti",
    gmtOffset: "UTC -10:00",
    selected: "",
  },
  {
    countryCode: "TF",
    countryName: "French Southern Territories",
    timeZone: "Indian/Kerguelen",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "GA",
    countryName: "Gabon",
    timeZone: "Africa/Libreville",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "GM",
    countryName: "Gambia",
    timeZone: "Africa/Banjul",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "GE",
    countryName: "Georgia",
    timeZone: "Asia/Tbilisi",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "DE",
    countryName: "Germany",
    timeZone: "Europe/Berlin",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "DE",
    countryName: "Germany",
    timeZone: "Europe/Busingen",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "GH",
    countryName: "Ghana",
    timeZone: "Africa/Accra",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "GI",
    countryName: "Gibraltar",
    timeZone: "Europe/Gibraltar",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "GR",
    countryName: "Greece",
    timeZone: "Europe/Athens",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "GL",
    countryName: "Greenland",
    timeZone: "America/Danmarkshavn",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "GL",
    countryName: "Greenland",
    timeZone: "America/Nuuk",
    gmtOffset: "UTC -01:00",
    selected: "",
  },
  {
    countryCode: "GL",
    countryName: "Greenland",
    timeZone: "America/Scoresbysund",
    gmtOffset: "UTC -01:00",
    selected: "",
  },
  {
    countryCode: "GL",
    countryName: "Greenland",
    timeZone: "America/Thule",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "GD",
    countryName: "Grenada",
    timeZone: "America/Grenada",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "GP",
    countryName: "Guadeloupe",
    timeZone: "America/Guadeloupe",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "GU",
    countryName: "Guam",
    timeZone: "Pacific/Guam",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "GT",
    countryName: "Guatemala",
    timeZone: "America/Guatemala",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "GG",
    countryName: "Guernsey",
    timeZone: "Europe/Guernsey",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "GN",
    countryName: "Guinea",
    timeZone: "Africa/Conakry",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "GW",
    countryName: "Guinea-Bissau",
    timeZone: "Africa/Bissau",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "GY",
    countryName: "Guyana",
    timeZone: "America/Guyana",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "HT",
    countryName: "Haiti",
    timeZone: "America/Port-au-Prince",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "VA",
    countryName: "Holy See (Vatican City State)",
    timeZone: "Europe/Vatican",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "HN",
    countryName: "Honduras",
    timeZone: "America/Tegucigalpa",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "HK",
    countryName: "Hong Kong",
    timeZone: "Asia/Hong_Kong",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "HU",
    countryName: "Hungary",
    timeZone: "Europe/Budapest",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "IS",
    countryName: "Iceland",
    timeZone: "Atlantic/Reykjavik",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "IN",
    countryName: "India",
    timeZone: "Asia/Kolkata",
    gmtOffset: "UTC +05:30",
    selected: "selected",
  },
  {
    countryCode: "ID",
    countryName: "Indonesia",
    timeZone: "Asia/Jakarta",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "ID",
    countryName: "Indonesia",
    timeZone: "Asia/Jayapura",
    gmtOffset: "UTC +09:00",
    selected: "",
  },
  {
    countryCode: "ID",
    countryName: "Indonesia",
    timeZone: "Asia/Makassar",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "ID",
    countryName: "Indonesia",
    timeZone: "Asia/Pontianak",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "IR",
    countryName: "Iran, Islamic Republic of",
    timeZone: "Asia/Tehran",
    gmtOffset: "UTC +03:30",
    selected: "",
  },
  {
    countryCode: "IQ",
    countryName: "Iraq",
    timeZone: "Asia/Baghdad",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "IE",
    countryName: "Ireland",
    timeZone: "Europe/Dublin",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "IM",
    countryName: "Isle of Man",
    timeZone: "Europe/Isle_of_Man",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "IL",
    countryName: "Israel",
    timeZone: "Asia/Jerusalem",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "IT",
    countryName: "Italy",
    timeZone: "Europe/Rome",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "JM",
    countryName: "Jamaica",
    timeZone: "America/Jamaica",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "JP",
    countryName: "Japan",
    timeZone: "Asia/Tokyo",
    gmtOffset: "UTC +09:00",
    selected: "",
  },
  {
    countryCode: "JE",
    countryName: "Jersey",
    timeZone: "Europe/Jersey",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "JO",
    countryName: "Jordan",
    timeZone: "Asia/Amman",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    timeZone: "Asia/Almaty",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    timeZone: "Asia/Aqtau",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    timeZone: "Asia/Aqtobe",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    timeZone: "Asia/Atyrau",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    timeZone: "Asia/Oral",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    timeZone: "Asia/Qostanay",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    timeZone: "Asia/Qyzylorda",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "KE",
    countryName: "Kenya",
    timeZone: "Africa/Nairobi",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "KI",
    countryName: "Kiribati",
    timeZone: "Pacific/Kanton",
    gmtOffset: "UTC +13:00",
    selected: "",
  },
  {
    countryCode: "KI",
    countryName: "Kiribati",
    timeZone: "Pacific/Kiritimati",
    gmtOffset: "UTC +14:00",
    selected: "",
  },
  {
    countryCode: "KI",
    countryName: "Kiribati",
    timeZone: "Pacific/Tarawa",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "KP",
    countryName: "Korea, Democratic People's Republic of",
    timeZone: "Asia/Pyongyang",
    gmtOffset: "UTC +09:00",
    selected: "",
  },
  {
    countryCode: "KR",
    countryName: "Korea, Republic of",
    timeZone: "Asia/Seoul",
    gmtOffset: "UTC +09:00",
    selected: "",
  },
  {
    countryCode: "KW",
    countryName: "Kuwait",
    timeZone: "Asia/Kuwait",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "KG",
    countryName: "Kyrgyzstan",
    timeZone: "Asia/Bishkek",
    gmtOffset: "UTC +06:00",
    selected: "",
  },
  {
    countryCode: "LA",
    countryName: "Lao People's Democratic Republic",
    timeZone: "Asia/Vientiane",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "LV",
    countryName: "Latvia",
    timeZone: "Europe/Riga",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "LB",
    countryName: "Lebanon",
    timeZone: "Asia/Beirut",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "LS",
    countryName: "Lesotho",
    timeZone: "Africa/Maseru",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "LR",
    countryName: "Liberia",
    timeZone: "Africa/Monrovia",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "LY",
    countryName: "Libya",
    timeZone: "Africa/Tripoli",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "LI",
    countryName: "Liechtenstein",
    timeZone: "Europe/Vaduz",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "LT",
    countryName: "Lithuania",
    timeZone: "Europe/Vilnius",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "LU",
    countryName: "Luxembourg",
    timeZone: "Europe/Luxembourg",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "MO",
    countryName: "Macao",
    timeZone: "Asia/Macau",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "MK",
    countryName: "Macedonia, the Former Yugoslav Republic of",
    timeZone: "Europe/Skopje",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "MG",
    countryName: "Madagascar",
    timeZone: "Indian/Antananarivo",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "MW",
    countryName: "Malawi",
    timeZone: "Africa/Blantyre",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "MY",
    countryName: "Malaysia",
    timeZone: "Asia/Kuala_Lumpur",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "MY",
    countryName: "Malaysia",
    timeZone: "Asia/Kuching",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "MV",
    countryName: "Maldives",
    timeZone: "Indian/Maldives",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "ML",
    countryName: "Mali",
    timeZone: "Africa/Bamako",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "MT",
    countryName: "Malta",
    timeZone: "Europe/Malta",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "MH",
    countryName: "Marshall Islands",
    timeZone: "Pacific/Kwajalein",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "MH",
    countryName: "Marshall Islands",
    timeZone: "Pacific/Majuro",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "MQ",
    countryName: "Martinique",
    timeZone: "America/Martinique",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "MR",
    countryName: "Mauritania",
    timeZone: "Africa/Nouakchott",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "MU",
    countryName: "Mauritius",
    timeZone: "Indian/Mauritius",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "YT",
    countryName: "Mayotte",
    timeZone: "Indian/Mayotte",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Bahia_Banderas",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Cancun",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Chihuahua",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Ciudad_Juarez",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Hermosillo",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Matamoros",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Mazatlan",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Merida",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Mexico_City",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Monterrey",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Ojinaga",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    timeZone: "America/Tijuana",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "FM",
    countryName: "Micronesia, Federated States of",
    timeZone: "Pacific/Chuuk",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "FM",
    countryName: "Micronesia, Federated States of",
    timeZone: "Pacific/Kosrae",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "FM",
    countryName: "Micronesia, Federated States of",
    timeZone: "Pacific/Pohnpei",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "MD",
    countryName: "Moldova, Republic of",
    timeZone: "Europe/Chisinau",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "MC",
    countryName: "Monaco",
    timeZone: "Europe/Monaco",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "MN",
    countryName: "Mongolia",
    timeZone: "Asia/Choibalsan",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "MN",
    countryName: "Mongolia",
    timeZone: "Asia/Hovd",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "MN",
    countryName: "Mongolia",
    timeZone: "Asia/Ulaanbaatar",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "ME",
    countryName: "Montenegro",
    timeZone: "Europe/Podgorica",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "MS",
    countryName: "Montserrat",
    timeZone: "America/Montserrat",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "MA",
    countryName: "Morocco",
    timeZone: "Africa/Casablanca",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "MA",
    countryName: "Morocco",
    timeZone: "Africa/El_Aaiun",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "MZ",
    countryName: "Mozambique",
    timeZone: "Africa/Maputo",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "MM",
    countryName: "Myanmar",
    timeZone: "Asia/Yangon",
    gmtOffset: "UTC +06:30",
    selected: "",
  },
  {
    countryCode: "NA",
    countryName: "Namibia",
    timeZone: "Africa/Windhoek",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "NR",
    countryName: "Nauru",
    timeZone: "Pacific/Nauru",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "NP",
    countryName: "Nepal",
    timeZone: "Asia/Kathmandu",
    gmtOffset: "UTC +05:45",
    selected: "",
  },
  {
    countryCode: "NL",
    countryName: "Netherlands",
    timeZone: "Europe/Amsterdam",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "NC",
    countryName: "New Caledonia",
    timeZone: "Pacific/Noumea",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "NZ",
    countryName: "New Zealand",
    timeZone: "Pacific/Auckland",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "NZ",
    countryName: "New Zealand",
    timeZone: "Pacific/Chatham",
    gmtOffset: "UTC +12:45",
    selected: "",
  },
  {
    countryCode: "NI",
    countryName: "Nicaragua",
    timeZone: "America/Managua",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "NE",
    countryName: "Niger",
    timeZone: "Africa/Niamey",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "NG",
    countryName: "Nigeria",
    timeZone: "Africa/Lagos",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "NU",
    countryName: "Niue",
    timeZone: "Pacific/Niue",
    gmtOffset: "UTC -11:00",
    selected: "",
  },
  {
    countryCode: "NF",
    countryName: "Norfolk Island",
    timeZone: "Pacific/Norfolk",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "MP",
    countryName: "Northern Mariana Islands",
    timeZone: "Pacific/Saipan",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "NO",
    countryName: "Norway",
    timeZone: "Europe/Oslo",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "OM",
    countryName: "Oman",
    timeZone: "Asia/Muscat",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "PK",
    countryName: "Pakistan",
    timeZone: "Asia/Karachi",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "PW",
    countryName: "Palau",
    timeZone: "Pacific/Palau",
    gmtOffset: "UTC +09:00",
    selected: "",
  },
  {
    countryCode: "PS",
    countryName: "Palestine, State of",
    timeZone: "Asia/Gaza",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "PS",
    countryName: "Palestine, State of",
    timeZone: "Asia/Hebron",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "PA",
    countryName: "Panama",
    timeZone: "America/Panama",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "PG",
    countryName: "Papua New Guinea",
    timeZone: "Pacific/Bougainville",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "PG",
    countryName: "Papua New Guinea",
    timeZone: "Pacific/Port_Moresby",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "PY",
    countryName: "Paraguay",
    timeZone: "America/Asuncion",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "PE",
    countryName: "Peru",
    timeZone: "America/Lima",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "PH",
    countryName: "Philippines",
    timeZone: "Asia/Manila",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "PN",
    countryName: "Pitcairn",
    timeZone: "Pacific/Pitcairn",
    gmtOffset: "UTC -08:00",
    selected: "",
  },
  {
    countryCode: "PL",
    countryName: "Poland",
    timeZone: "Europe/Warsaw",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "PT",
    countryName: "Portugal",
    timeZone: "Atlantic/Azores",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "PT",
    countryName: "Portugal",
    timeZone: "Atlantic/Madeira",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "PT",
    countryName: "Portugal",
    timeZone: "Europe/Lisbon",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "PR",
    countryName: "Puerto Rico",
    timeZone: "America/Puerto_Rico",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "QA",
    countryName: "Qatar",
    timeZone: "Asia/Qatar",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "RO",
    countryName: "Romania",
    timeZone: "Europe/Bucharest",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Anadyr",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Barnaul",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Chita",
    gmtOffset: "UTC +09:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Irkutsk",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Kamchatka",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Khandyga",
    gmtOffset: "UTC +09:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Krasnoyarsk",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Magadan",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Novokuznetsk",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Novosibirsk",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Omsk",
    gmtOffset: "UTC +06:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Sakhalin",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Srednekolymsk",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Tomsk",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Ust-Nera",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Vladivostok",
    gmtOffset: "UTC +10:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Yakutsk",
    gmtOffset: "UTC +09:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Asia/Yekaterinburg",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Europe/Astrakhan",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Europe/Kaliningrad",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Europe/Kirov",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Europe/Moscow",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Europe/Samara",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Europe/Saratov",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Europe/Ulyanovsk",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation",
    timeZone: "Europe/Volgograd",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "RW",
    countryName: "Rwanda",
    timeZone: "Africa/Kigali",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "RE",
    countryName: "Réunion",
    timeZone: "Indian/Reunion",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "BL",
    countryName: "Saint Barthélemy",
    timeZone: "America/St_Barthelemy",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "SH",
    countryName: "Saint Helena, Ascension and Tristan da Cunha",
    timeZone: "Atlantic/St_Helena",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "KN",
    countryName: "Saint Kitts and Nevis",
    timeZone: "America/St_Kitts",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "LC",
    countryName: "Saint Lucia",
    timeZone: "America/St_Lucia",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "MF",
    countryName: "Saint Martin (French part)",
    timeZone: "America/Marigot",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "PM",
    countryName: "Saint Pierre and Miquelon",
    timeZone: "America/Miquelon",
    gmtOffset: "UTC -02:00",
    selected: "",
  },
  {
    countryCode: "VC",
    countryName: "Saint Vincent and the Grenadines",
    timeZone: "America/St_Vincent",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "WS",
    countryName: "Samoa",
    timeZone: "Pacific/Apia",
    gmtOffset: "UTC +13:00",
    selected: "",
  },
  {
    countryCode: "SM",
    countryName: "San Marino",
    timeZone: "Europe/San_Marino",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "ST",
    countryName: "Sao Tome and Principe",
    timeZone: "Africa/Sao_Tome",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "SA",
    countryName: "Saudi Arabia",
    timeZone: "Asia/Riyadh",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "SN",
    countryName: "Senegal",
    timeZone: "Africa/Dakar",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "RS",
    countryName: "Serbia",
    timeZone: "Europe/Belgrade",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "SC",
    countryName: "Seychelles",
    timeZone: "Indian/Mahe",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "SL",
    countryName: "Sierra Leone",
    timeZone: "Africa/Freetown",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "SG",
    countryName: "Singapore",
    timeZone: "Asia/Singapore",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "SX",
    countryName: "Sint Maarten (Dutch part)",
    timeZone: "America/Lower_Princes",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "SK",
    countryName: "Slovakia",
    timeZone: "Europe/Bratislava",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "SI",
    countryName: "Slovenia",
    timeZone: "Europe/Ljubljana",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "SB",
    countryName: "Solomon Islands",
    timeZone: "Pacific/Guadalcanal",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "SO",
    countryName: "Somalia",
    timeZone: "Africa/Mogadishu",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "ZA",
    countryName: "South Africa",
    timeZone: "Africa/Johannesburg",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "GS",
    countryName: "South Georgia and the South Sandwich Islands",
    timeZone: "Atlantic/South_Georgia",
    gmtOffset: "UTC -02:00",
    selected: "",
  },
  {
    countryCode: "SS",
    countryName: "South Sudan",
    timeZone: "Africa/Juba",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "ES",
    countryName: "Spain",
    timeZone: "Africa/Ceuta",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "ES",
    countryName: "Spain",
    timeZone: "Atlantic/Canary",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "ES",
    countryName: "Spain",
    timeZone: "Europe/Madrid",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "LK",
    countryName: "Sri Lanka",
    timeZone: "Asia/Colombo",
    gmtOffset: "UTC +05:30",
    selected: "",
  },
  {
    countryCode: "SD",
    countryName: "Sudan",
    timeZone: "Africa/Khartoum",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "SR",
    countryName: "Suriname",
    timeZone: "America/Paramaribo",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "SJ",
    countryName: "Svalbard and Jan Mayen",
    timeZone: "Arctic/Longyearbyen",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "SZ",
    countryName: "Swaziland",
    timeZone: "Africa/Mbabane",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "SE",
    countryName: "Sweden",
    timeZone: "Europe/Stockholm",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "CH",
    countryName: "Switzerland",
    timeZone: "Europe/Zurich",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "SY",
    countryName: "Syrian Arab Republic",
    timeZone: "Asia/Damascus",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "TW",
    countryName: "Taiwan, Province of China",
    timeZone: "Asia/Taipei",
    gmtOffset: "UTC +08:00",
    selected: "",
  },
  {
    countryCode: "TJ",
    countryName: "Tajikistan",
    timeZone: "Asia/Dushanbe",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "TZ",
    countryName: "Tanzania, United Republic of",
    timeZone: "Africa/Dar_es_Salaam",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "TH",
    countryName: "Thailand",
    timeZone: "Asia/Bangkok",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "TL",
    countryName: "Timor-Leste",
    timeZone: "Asia/Dili",
    gmtOffset: "UTC +09:00",
    selected: "",
  },
  {
    countryCode: "TG",
    countryName: "Togo",
    timeZone: "Africa/Lome",
    gmtOffset: "UTC",
    selected: "",
  },
  {
    countryCode: "TK",
    countryName: "Tokelau",
    timeZone: "Pacific/Fakaofo",
    gmtOffset: "UTC +13:00",
    selected: "",
  },
  {
    countryCode: "TO",
    countryName: "Tonga",
    timeZone: "Pacific/Tongatapu",
    gmtOffset: "UTC +13:00",
    selected: "",
  },
  {
    countryCode: "TT",
    countryName: "Trinidad and Tobago",
    timeZone: "America/Port_of_Spain",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "TN",
    countryName: "Tunisia",
    timeZone: "Africa/Tunis",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "TR",
    countryName: "Turkey",
    timeZone: "Europe/Istanbul",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "TM",
    countryName: "Turkmenistan",
    timeZone: "Asia/Ashgabat",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "TC",
    countryName: "Turks and Caicos Islands",
    timeZone: "America/Grand_Turk",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "TV",
    countryName: "Tuvalu",
    timeZone: "Pacific/Funafuti",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "UG",
    countryName: "Uganda",
    timeZone: "Africa/Kampala",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "UA",
    countryName: "Ukraine",
    timeZone: "Europe/Kyiv",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "UA",
    countryName: "Ukraine",
    timeZone: "Europe/Simferopol",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "AE",
    countryName: "United Arab Emirates",
    timeZone: "Asia/Dubai",
    gmtOffset: "UTC +04:00",
    selected: "",
  },
  {
    countryCode: "GB",
    countryName: "United Kingdom",
    timeZone: "Europe/London",
    gmtOffset: "UTC +01:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Adak",
    gmtOffset: "UTC -09:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Anchorage",
    gmtOffset: "UTC -08:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Boise",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Chicago",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Denver",
    gmtOffset: "UTC -06:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Detroit",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Indiana/Indianapolis",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Indiana/Knox",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Indiana/Marengo",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Indiana/Petersburg",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Indiana/Tell_City",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Indiana/Vevay",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Indiana/Vincennes",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Indiana/Winamac",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Juneau",
    gmtOffset: "UTC -08:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Kentucky/Louisville",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Kentucky/Monticello",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Los_Angeles",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Menominee",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Metlakatla",
    gmtOffset: "UTC -08:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/New_York",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Nome",
    gmtOffset: "UTC -08:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/North_Dakota/Beulah",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/North_Dakota/Center",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/North_Dakota/New_Salem",
    gmtOffset: "UTC -05:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Phoenix",
    gmtOffset: "UTC -07:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Sitka",
    gmtOffset: "UTC -08:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "America/Yakutat",
    gmtOffset: "UTC -08:00",
    selected: "",
  },
  {
    countryCode: "US",
    countryName: "United States",
    timeZone: "Pacific/Honolulu",
    gmtOffset: "UTC -10:00",
    selected: "",
  },
  {
    countryCode: "UM",
    countryName: "United States Minor Outlying Islands",
    timeZone: "Pacific/Midway",
    gmtOffset: "UTC -11:00",
    selected: "",
  },
  {
    countryCode: "UM",
    countryName: "United States Minor Outlying Islands",
    timeZone: "Pacific/Wake",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "UY",
    countryName: "Uruguay",
    timeZone: "America/Montevideo",
    gmtOffset: "UTC -03:00",
    selected: "",
  },
  {
    countryCode: "UZ",
    countryName: "Uzbekistan",
    timeZone: "Asia/Samarkand",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "UZ",
    countryName: "Uzbekistan",
    timeZone: "Asia/Tashkent",
    gmtOffset: "UTC +05:00",
    selected: "",
  },
  {
    countryCode: "VU",
    countryName: "Vanuatu",
    timeZone: "Pacific/Efate",
    gmtOffset: "UTC +11:00",
    selected: "",
  },
  {
    countryCode: "VE",
    countryName: "Venezuela, Bolivarian Republic of",
    timeZone: "America/Caracas",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "VN",
    countryName: "Viet Nam",
    timeZone: "Asia/Ho_Chi_Minh",
    gmtOffset: "UTC +07:00",
    selected: "",
  },
  {
    countryCode: "VG",
    countryName: "Virgin Islands, British",
    timeZone: "America/Tortola",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "VI",
    countryName: "Virgin Islands, U.S.",
    timeZone: "America/St_Thomas",
    gmtOffset: "UTC -04:00",
    selected: "",
  },
  {
    countryCode: "WF",
    countryName: "Wallis and Futuna",
    timeZone: "Pacific/Wallis",
    gmtOffset: "UTC +12:00",
    selected: "",
  },
  {
    countryCode: "YE",
    countryName: "Yemen",
    timeZone: "Asia/Aden",
    gmtOffset: "UTC +03:00",
    selected: "",
  },
  {
    countryCode: "ZM",
    countryName: "Zambia",
    timeZone: "Africa/Lusaka",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "ZW",
    countryName: "Zimbabwe",
    timeZone: "Africa/Harare",
    gmtOffset: "UTC +02:00",
    selected: "",
  },
  {
    countryCode: "AX",
    countryName: "Åland Islands",
    timeZone: "Europe/Mariehamn",
    gmtOffset: "UTC +03:00",
  },
];


// Create Main Div

let mainDiv = document.createElement('div');
mainDiv.id = 'main';

// console.log(new Date().toLocaleString("en-US", { timeZone: "Europe/London" }));
// Creates Div for Countries
let getTimeZone = "Asia/Kolkata";
let countries = document.createElement("div");
countries.classList.add("countryContainer");

// Creates Form for Selecting Countries
let createForm = document.createElement("form");
createForm.setAttribute("onchange", "updateClock(getTimeZone)");

// Create Dropdown of Countries
let dropDown = document.createElement("select");
dropDown.name = "countriesDropdown";
dropDown.id = "countriesDropdown";
dropDown.classList.add("form_control");
dropDown.setAttribute('autofocus', true);

// Populating the Dropdown
timeZones.forEach(function (zone) {
  var dropDownItem = document.createElement("option");
  dropDownItem.value = zone.timeZone;
  dropDownItem.textContent = zone.countryName + " - " + zone.timeZone + " ("+ zone.gmtOffset +")";
  if (zone.selected == "selected") {
    dropDownItem.setAttribute("selected", true);
  }

  // Appends every dropdown item to the list
  dropDown.appendChild(dropDownItem);
});

// add dropdown to the form element
createForm.appendChild(dropDown);

// add form to the created div
mainDiv.append(createForm);
document.body.append(mainDiv);

// Event Listener for the change in dropdown
const timeZoneDropDown = document.getElementById("countriesDropdown");
timeZoneDropDown.addEventListener("change", function (e) {
    getTimeZone = timeZoneDropDown.value;
});

setInterval(() => {
    updateClock(getTimeZone);
}, 1000);

let clock = document.createElement("div");
clock.classList.add("clock");
let hrs = document.createElement("span");
hrs.id = "hr";
let min = document.createElement("span");
min.id = "mn";
let sec = document.createElement("span");
sec.id = "sc";

let dayData = document.createElement("div");
let dateData = document.createElement("span");
let monthData = document.createElement("span");
let yearData = document.createElement("span");

function updateClock(getTimeZone) {
    let date = new Date().toLocaleString("en-US", {
        timeZone: getTimeZone,
        hour12: false,
    });
    dateArray = date.split(",");
  getTime = dateArray[1];
  getDates = dateArray[0];
  getTimeArray = getTime.split(":");
  getHours = getTimeArray[0];
  getMinutes = getTimeArray[1];
  getSeconds = getTimeArray[2];
  
  getDateArray = getDates.split("/");
  getDate = getDateArray[1];
  getMonth = getDateArray[0];
  getFullYear = getDateArray[2];
  
  hrs.textContent = getHours;
  min.textContent = getMinutes;
  
  dateData.id = "day";
  dateData.textContent = getDate + " / ";
  monthData.id = "month";
  monthData.textContent = getMonth + " / ";
  yearData.id = "year";
  yearData.textContent = getFullYear;
  dayData.classList.add("dayData");
  dayData.append(dateData, monthData, yearData);
  
  function updateTime() {
      hrs.textContent = getHours;
      min.textContent = getMinutes;
      sec.textContent = getSeconds;
      date = new Date().toLocaleString("en-US", {
          timeZone: getTimeZone,
          hour12: false,
        });
    }
    setInterval(updateTime, 1000);
    
  clock.append(hrs, min, sec);
}

mainDiv.append(clock, dayData);